output_path: "" 
x_squares: 10
y_squares: 14
squares_size: 0.0280
markers_size: 0.0168
px_img_size_x: 1400
px_img_size_y: 2000
margins: 10
borderBits: 1
showImage: false
dictionaryId: 10
        